name: Schedule Freeze Time

on:
  schedule:
    - cron: "0 13 * * *"  # 9:00 AM RD (UTC-4)
  workflow_dispatch:

jobs:
  schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_PAT }}
      
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      
      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
      
      - name: Install project (editable)
        run: |
          source .venv/bin/activate
          pip install -e .
      
      - name: Load .env
        run: |
          echo "ESPN_LEAGUE_ID=${{ secrets.ESPN_LEAGUE_ID }}" >> .env
          echo "ESPN_S2=${{ secrets.ESPN_S2 }}" >> .env
          echo "ESPN_SWID=${{ secrets.ESPN_SWID }}" >> .env
      
      - name: Schedule freeze time
        run: |
          source .venv/bin/activate
          python src/fantasyxi/pipeline/schedule_freeze_time.py
      
      - name: Commit freeze_time.json
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add data/processed/freeze_time.json
          git commit -m "🕒 Actualizar freeze_time para hoy" || echo "No changes to commit"
          git push origin main